### ISSUE TITLE
Enabling lighthubert with setup.py?

### ISSUE THREAD

**Issue by leo19941227** [mechanicalsea/lighthubert#1]
Hello!

Thanks for the great work!
My colleague @edward0804 and I are thinking about integrating lighthubert into S3PRL to enable more research.
Instead of copying all the lighthubert code into S3PRL, we are wondering whether adding a setup.py in this repo would be a good alternative so that we can simply install it, enabling lighthubert in the S3PRL codebase, and link the interested user to this repo for the actual implementation.

I have made a [minimal fork](https://github.com/s3prl/lighthubert) for this and so lighthubert can be installed in S3PRL after this commit s3prl/s3prl@07c5bd8692ce481cea5e0190c2cabf759300799b, and @edward0804 is working on adding a wrapper for lighthubert. Do you think it would be nice to add an official setup.py ? :)

Thanks!

**Comment by mechanicalsea** [comment]
Hi!

Thanks for your attention! We are glad to add a setup.py in the repository.

We have added and tested a setup.py after this commit [mechanicalsea/lighthubert@8a95a95](https://github.com/mechanicalsea/lighthubert/commit/8a95a95d5d16762f54625dba8054294969f6fd23). Since the S3PRL may support Python >= 3.6, we also tested the lighthubert inference on the Python 3.6, 3.7, and 3.8. Also, we provided requirements and installation in [README.md](https://github.com/mechanicalsea/lighthubert#requirements-and-installation). Once you install lighthubert, it is easy to use it as follows.

```python
from lighthubert import LightHuBERT, LightHuBERTConfig
# ...
```

If you have any questions or problems, please continue to comment.

Thanks again for your attention. We look forward to having a great S3PRL lighthubert!

Best Wishes.

**Comment by leo19941227** [comment]
Cool! Thanks for working on this!
Will let you know after we merge this model!

Sincerely,
Leo
